name: clash

services:
  clash:
    image: metacubex/mihomo:latest
    container_name: clash
    restart: unless-stopped
    volumes:
      - ./config:/root/.config/mihomo
    networks: [nginx, clash]
    ports:
      - "${CLASH_EXPORT_HOST:-127.0.0.1}:${CLASH_EXPORT_PORT:-9870}:7890"
  yacd:
    image: haishanh/yacd
    container_name: clash-yacd
    restart: unless-stopped
    networks: [nginx, clash]

networks:
  nginx:
    external: true
  clash:
    name: clash
