name: clash

services:
  clash:
    image: metacubex/mihomo:latest
    container_name: clash
    restart: unless-stopped
    volumes:
      - ./config:/root/.config/mihomo
    networks: [nginx, clash]
  metacubexd:
    container_name: metacubexd
    image: ghcr.io/metacubex/metacubexd:latest
    restart: unless-stopped
    environment:
      DEFAULT_BACKEND_URL: ${MCXD_DEFAULT_BACKEND_URL}
    networks: [nginx, clash]

networks:
  nginx:
    external: true
  clash:
    name: clash
