name: clash

services:
  clash:
    image: metacubex/mihomo:latest
    container_name: clash
    restart: unless-stopped
    volumes:
      - ./config:/root/.config/mihomo
    networks: [nginx, clash]
  yacd:
    image: haishanh/yacd
    container_name: clash-yacd
    restart: unless-stopped
    networks: [nginx, clash]

networks:
  nginx:
    external: true
  clash:
    name: clash
