name: portainer

services:
  portainer:
    image: portainer/portainer-ce:lts
    restart: unless-stopped
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [nginx]

networks:
  nginx:
    external: true
