name: portainer

services:
  portainer:
    image: portainer/portainer-ce:lts
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ${HOST_DOCKER_SOCKET}:/var/run/docker.sock
    env_file: .env
    networks: [nginx]

networks:
  nginx:
    external: true
