name: beszel-agent

services:
  beszel-agent:
    # image: henrygd/beszel-agent:latest
    image: henrygd/beszel-agent-intel:latest
    container_name: beszel-agent
    restart: always
    network_mode: container:tailscale
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./agent:/var/lib/beszel-agent
    env_file: .env
