name: syncthing

services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: ${SYNCTHING_HOSTNAME}
    env_file: .env
    volumes:
      - ./data:/var/syncthing
    ports:
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    networks: [nginx]
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  nginx:
    external: true
